### ISSUE TITLE
请教关于预测的问题

### ISSUE THREAD

**Issue by yazheng0307** [LBH1024/CAN#25]
你好，我想测试一下模型在印刷体公式识别上的效果，测试的ExpRate达到0.8，但是另外使用外来的图片预测的时候，结果总是一串相同的字符，这会是什么原因引起的呢？

输入图片：
![00000495](https://user-images.githubusercontent.com/50820616/202946217-03333ac7-16e3-4abd-9d64-687af9868390.png)

程序结果：
![92959e6c1ddf7e6c0be4ba116882d78](https://user-images.githubusercontent.com/50820616/202946248-e668071a-ea14-4112-81f2-2d741c61b332.jpg)

**Comment by SuperHHzy** [comment]
请问一下，你的印刷体公式数据集是使用的IM2LATEX-100K这个数据集吗？如果是使用印刷体公式的数据集来训练模型需要修改什么参数吗？谢谢

**Comment by yazheng0307** [comment]
> 
用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改

**Comment by yazheng0307** [comment]
> 用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改



> 请问一下，你的印刷体公式数据集是使用的IM2LATEX-100K这个数据集吗？如果是使用印刷体公式的数据集来训练模型需要修改什么参数吗？谢谢

用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改

**Comment by SuperHHzy** [comment]
可以分享一下这个子集吗？

**Comment by SuperHHzy** [comment]
> > 用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改
> 
> > 请问一下，你的印刷体公式数据集是使用的IM2LATEX-100K这个数据集吗？如果是使用印刷体公式的数据集来训练模型需要修改什么参数吗？谢谢
> 
> 用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改

可以分享一下这个子集吗？

**Comment by SuperHHzy** [comment]
> > 用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改
> 
> > 请问一下，你的印刷体公式数据集是使用的IM2LATEX-100K这个数据集吗？如果是使用印刷体公式的数据集来训练模型需要修改什么参数吗？谢谢
> 
> 用的数据集是IM2LATEX-100K的子集，需要改config里面的字典长度，根据自己的数据集字典长度修改

config里面哪个参数是关于字典长度的呢？我好像没有找到那个参数。谢谢

**Comment by SuperHHzy** [comment]
你好，我在用IM2LATEX-100K这个数据集进行训练的时候，我把字典换成了IM2LATEX-100K这个数据集对应的字典，为什么会报这个错误呢？你有出现这个错误吗？
![image](https://user-images.githubusercontent.com/107484371/203512749-6ddf49f1-df3d-4d65-8e0d-06259f4c6a72.png)

**Comment by SuperHHzy** [comment]
你好，想请问你使用的IM2LATEX-100K的子集，是怎么生成PKL文件的呢？

**Comment by Conan-jine** [comment]
> 你好，我想测试一下模型在印刷体公式识别上的效果，测试的ExpRate达到0.8，但是另外使用外来的图片预测的时候，结果总是一串相同的字符，这会是什么原因引起的呢？
> 
> 输入图片： ![00000495](https://user-images.githubusercontent.com/50820616/202946217-03333ac7-16e3-4abd-9d64-687af9868390.png)
> 
> 程序结果： ![92959e6c1ddf7e6c0be4ba116882d78](https://user-images.githubusercontent.com/50820616/202946248-e668071a-ea14-4112-81f2-2d741c61b332.jpg)

你好！我想问问你测试的时候是咋样操作的
我设置了checkpoint路径，但是运行之后报错
```bash
Traceback (most recent call last):
  File "inference.py", line 46, in <module>
    load_checkpoint(model, None, params['checkpoint'])
  File "/home/conan/Documents/VscodeFiles/CAN/utils.py", line 69, in load_checkpoint
    state = torch.load(path, map_location='cpu')
  File "/home/conan/App/anaconda3/envs/hmer-can/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/conan/App/anaconda3/envs/hmer-can/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```
我的config配置是
```
optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
checkpoint: 'config.yaml'
log_dir: 'logs'
```

我运行的代码是
```bash
python inference.py --dataset CROHME
```

**Comment by SuperHHzy** [comment]
你好，我子集制作了一个IM2LATEX-100K的子集，训练集大约有10000张图片，验证集大概2000张图片，我只修改了config里面的字典长度，训练了220个epoch之后，ExpRate只有21%左右，不知道这是什么原因呢？不知可否告知一下你的数据集大小呢？

**Comment by ZCappuccino** [comment]
您好，打扰了，我想使用印刷体数据集进行训练，但是当我把config中与数据集相关的配置文件转换成自己的以后，出现了图中所示的问题。请问您在训练运行的过程中出现了类似的问题吗？可以帮忙提一点建议吗？
![屏幕截图_20221225_203552](https://user-images.githubusercontent.com/92078296/209468182-22a7d146-0df8-4969-bf2f-949621b7917b.png)

**Comment by Yuxiang1995** [comment]
> 您好，打扰了，我想使用印刷体数据集进行训练，但是当我把config中与数据集相关的配置文件转换成自己的以后，出现了图中所示的问题。请问您在训练运行的过程中出现了类似的问题吗？可以帮忙提一点建议吗？ ![屏幕截图_20221225_203552](https://user-images.githubusercontent.com/92078296/209468182-22a7d146-0df8-4969-bf2f-949621b7917b.png)

读图的时候读灰度图

**Comment by Yuxiang1995** [comment]
> 你好，我想测试一下模型在印刷体公式识别上的效果，测试的ExpRate达到0.8，但是另外使用外来的图片预测的时候，结果总是一串相同的字符，这会是什么原因引起的呢？
> 
> 输入图片： ![00000495](https://user-images.githubusercontent.com/50820616/202946217-03333ac7-16e3-4abd-9d64-687af9868390.png)
> 
> 程序结果： ![92959e6c1ddf7e6c0be4ba116882d78](https://user-images.githubusercontent.com/50820616/202946248-e668071a-ea14-4112-81f2-2d741c61b332.jpg

@yazheng0307 我拿数据集之外的图片来测效果也很差，似乎模型的泛化能力不好？请问你解决了吗

**Comment by SuperHHzy** [comment]
> > 你好，我想测试一下模型在印刷体公式识别上的效果，测试的ExpRate达到0.8，但是另外使用外来的图片预测的时候，结果总是一串相同的字符，这会是什么原因引起的呢？
> > 输入图片： ![00000495](https://user-images.githubusercontent.com/50820616/202946217-03333ac7-16e3-4abd-9d64-687af9868390.png)
> > 程序结果： ![92959e6c1ddf7e6c0be4ba116882d78](https://user-images.githubusercontent.com/50820616/202946248-e668071a-ea14-4112-81f2-2d741c61b332.jpg
> 
> @yazheng0307 我拿数据集之外的图片来测效果也很差，似乎模型的泛化能力不好？请问你解决了吗

你使用的是自己预训练的模型吗？请问模型的准确率如何呢？

**Comment by limaopeng1** [comment]
> > 你好，我想测试一下模型在印刷体公式识别上的效果，测试的ExpRate达到0.8，但是另外使用外来的图片预测的时候，结果总是一串相同的字符，这会是什么原因引起的呢？
> > 输入图片： ![00000495](https://user-images.githubusercontent.com/50820616/202946217-03333ac7-16e3-4abd-9d64-687af9868390.png)
> > 程序结果： ![92959e6c1ddf7e6c0be4ba116882d78](https://user-images.githubusercontent.com/50820616/202946248-e668071a-ea14-4112-81f2-2d741c61b332.jpg
> 
> @yazheng0307 我拿数据集之外的图片来测效果也很差，似乎模型的泛化能力不好？请问你解决了吗

一样遇到这个问题，请问有人解决了吗

**Comment by SWHL** [comment]
我似乎也遇到这问题了，训练印刷体公式识别时，效果一直很差。
